### ISSUE TITLE
Error/Crash while emulating. 

### ISSUE THREAD

**Issue by RoRue** [GameTechDev/OpenGL-ES-3.0-Deferred-Rendering#3]
![image](https://user-images.githubusercontent.com/40343231/52163368-3f1ef000-26e1-11e9-99ed-5cfe2c25735b.png)

Hi,

I have come across some issues while emulating. The program crashes as soon as it starts.
Same thing on my real device.
I am emulating a Nexus5 with API lvl 18.

Have you experienced something similar?

Regards

**Comment by RoRue** [comment]
I actually got it to work now. 
Maybe you could help me with something else:
I am trying to load a different model but cant seem to find where you load the obj files...

**Comment by JeffersonMontgomery-Intel** [comment]
Glad you were able to resolve it.

Scene loading appears to be here: https://github.com/GameTechDev/OpenGL-ES-3.0-Deferred-Rendering/blob/149ac95e12c9b35d5c1d3b78200258f1907bc4dc/src/scene.cpp#L603

**Comment by RoRue** [comment]
Hi again, 
sorry for bothering you. But the model is not loading for me. The app just crashes when I put in a different model.
What do I have to do? You are putting in a strange file with .mtl that I have never seen before. Do I need that for it to work?

**Comment by RoRue** [comment]
Could you tell me how to create new lights? 
Because I only figured out how to add more of the lights you already implemented. 
But I want to add different lights. 

Would be greatly appreciated! :)
