### ISSUE TITLE
Deferred Rendering Method missing

### ISSUE THREAD

**Issue by RoRue** [GameTechDev/OpenGL-ES-3.0-Deferred-Rendering#4]
Hi,

you said there a 3 different rendering Methods in your project. However only 2 are working. Deferred Lighting and Forward Rendering. Deferred Rendering is not showing up, even though it is in initialized in your project.
Could you please check why this is happening? Maybe I need to initialize deferred rendering somewhere else?

I am looking forward to your answer.

**Comment by Tianji95** [comment]
> Hi,
> 
> you said there a 3 different rendering Methods in your project. However only 2 are working. Deferred Lighting and Forward Rendering. Deferred Rendering is not showing up, even though it is in initialized in your project.
> Could you please check why this is happening? Maybe I need to initialize deferred rendering somewhere else?
> 
> I am looking forward to your answer.

Hi, I meet this same problem now, so have you find what was wrong in the project? it seems that there are some problems with the shader "geometryfragment.glsl"

**Comment by Tianji95** [comment]
Ok, I have solved this problem by simply change the "geometryfragment.glsl" and "geometryvertex.glsl" to gles 3.0 ,it is somewhat like that:

geometryfragment.glsl:
```
#version 300 es
precision highp float;
uniform sampler2D s_Albedo;
uniform sampler2D s_Normal;

uniform vec3    u_SpecularColor;
uniform float   u_SpecularPower;
uniform float   u_SpecularCoefficient;

in vec3 v_NormalVS;
in vec3 v_TangentVS;
in vec3 v_BitangentVS;
in vec2 v_TexCoord;

layout(location = 0) out vec4 fragColor0;
layout(location = 1) out vec4 fragColor1;

vec4 encode (vec3 normal)
{
    float p = sqrt(normal.z*8.0+8.0);
    return vec4(normal.xy/p + 0.5,0,0);
}

void main(void) {
    /** Load texture values
     */
    vec3 albedo = texture(s_Albedo, v_TexCoord.xy).rgb;
    vec3 normal = normalize(texture(s_Normal, v_TexCoord.xy).rgb*2.0 - 1.0);
    vec3 specular_color = u_SpecularCoefficient * u_SpecularColor;
    
    vec3 N = normalize(v_NormalVS);
    vec3 T = normalize(v_TangentVS);
    vec3 B = normalize(v_BitangentVS);

    mat3 TBN = mat3(T, B, N);
    normal = normalize(TBN*normal);

    /** GBuffer format
     *  [0] RGB: Albedo
     *  [1] RGB: VS Normal
     *  [2] R: Depth
     */
    fragColor0 = vec4(albedo, 1.0);
    fragColor1 = encode(normal);
}
```
geometryvertex.glsl:
```
#version 300 es
uniform mat4 u_Projection;
uniform mat4 u_View;
uniform mat4 u_World;

in vec4 a_Position;
in vec3 a_Normal;
in vec3 a_Tangent;
in vec3 a_Bitangent;
in vec2 a_TexCoord;

out vec3 v_NormalVS;
out vec3 v_TangentVS;
out vec3 v_BitangentVS;
out vec2 v_TexCoord;

void main(void) {
    mat3 world3 = mat3(u_World);
    mat3 view3 = mat3(u_View);

    vec4 world_pos = u_World * a_Position;
    vec4 view_pos = u_View * world_pos;

    v_NormalVS = view3 * world3 * a_Normal;
    v_TangentVS = view3 * world3 * a_Tangent;
    v_BitangentVS = view3 * world3 * a_Bitangent;
    v_TexCoord = a_TexCoord;

    gl_Position = u_Projection * view_pos;
}
```
